---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	lead_researcher(lead_researcher)
	aws_expert(aws_expert)
	azure_expert(azure_expert)
	retrieve(retrieve)
	__end__([<p>__end__</p>]):::last
	__start__ --> lead_researcher;
	azure_expert -.-> __end__;
	azure_expert -. &nbsp;tools&nbsp; .-> retrieve;
	lead_researcher -.-> __end__;
	lead_researcher -.-> aws_expert;
	lead_researcher -.-> azure_expert;
	aws_expert --> __end__;
	retrieve --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
